name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      cert_password:
        description: 'Certificate decryption password'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build and Publish Nuget Package
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
            2.1.x
            3.1.x
            5.0.x
      - name: Build Package
        run:
          dotnet build -c Release ./src/BlendInteractive.Datastore/BlendInteractive.Datastore.csproj /p:ContinuousIntegrationBuild=true
      - name: Package Release
        run:           
          dotnet pack -c Release --no-build -o out ./src/BlendInteractive.Datastore/BlendInteractive.Datastore.csproj
      - name: Retrieve and decode signing cert
        run: echo $CERTIFICATE_BASE64 | base64 --decode > ./cert.p12
        env:
          CERTIFICATE_BASE64: ${{ secrets.CERTIFICATE_BASE64 }}
      - name: Sign package
        run: dotnet nuget sign ./out/*.nupkg --certificate-path ./cert.p12 --timestamper http://ts.ssl.com --certificate-password $CERT_PASSWORD
        env:
          CERT_PASSWORD: ${{ github.event.inputs.cert_password }}
      - name: Clean up signing cert
        run: rm ./cert.p12
      - name: Publish package to Nuget public registry
        run: dotnet nuget push ./out/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }} 
